name: Build Windows Static 5

on:
  workflow_dispatch:   # solo manual

jobs:
  build-windows-static:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-opencv
            mingw-w64-x86_64-libraw
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-cli11
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-wxwidgets3.2-msw
            mingw-w64-x86_64-wxwidgets3.2-common

      - name: Configure (CMake)
        shell: msys2 {0}
        run: |
          cmake -G "MinGW Makefiles" \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="-static"

      - name: Build
        shell: msys2 {0}
        run: cmake --build build --config Release --parallel

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: dynaRange-windows-static
          path: |
            build/rango.exe
            build/dynaRangeGui.exe