name: Build dynaRange for Windows (5) (Static Binaries + Installer)

on:
  workflow_dispatch:

jobs:
  build-windows-static:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2 and Static Dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-opencv
            mingw-w64-x86_64-libraw
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-cli11
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-wxwidgets

      # Paso redundante para asegurar wxWidgets (cambia a wxwidgets sin -gtk3)
      - name: Ensure wxWidgets is Installed
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-wxwidgets
        shell: msys2 {0}

      # Añadir MSYS2 bin al PATH global del job
      - name: Add MSYS2 mingw64 to Global PATH
        run: |
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
          echo "C:/msys64/usr/bin" >> $GITHUB_PATH
        shell: bash

      # Debug PATH y presencia de wx-config
      - name: Debug PATH and wx-config presence
        run: |
          echo $PATH
          ls /mingw64/bin | grep wx
        shell: msys2 {0}

      # Comprobar wx-config antes de CMake
      - name: Check wx-config
        run: |
          which wx-config
          wx-config --version
        shell: msys2 {0}

      - name: Configure CMake for Static Build
        run: |
          export PATH="/mingw64/bin:$PATH"
          export WXWIN="/mingw64"
          export wx_CONFIG_EXECUTABLE="/mingw64/bin/wx-config"
          cmake -B build \
            -G "MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            -DwxWidgets_CONFIG_EXECUTABLE="/mingw64/bin/wx-config"
        shell: msys2 {0}

      - name: Build
        run: cmake --build build --config Release
        shell: msys2 {0}

      - name: Verify Static Linking
        run: |
          ldd build/rango.exe || echo "rango.exe is statically linked (no dynamic deps found)"
          ldd build/dynaRangeGui.exe || echo "dynaRangeGui.exe is statically linked (no dynamic deps found)"
        shell: msys2 {0}

      - name: Create Portable Folder Structure
        run: |
          mkdir dynaRangePortable
          cp build/rango.exe dynaRangePortable/
          cp build/dynaRangeGui.exe dynaRangePortable/
          cp build/logo.png dynaRangePortable/
          cp favicon_owl.ico dynaRangePortable/
          cp favicon_noise.ico dynaRangePortable/
          if [ -f "crear_instalador_windows.nsi" ]; then
            cp crear_instalador_windows.nsi dynaRangePortable/
          fi
        shell: bash

      - name: Check for NSIS script
        id: check_nsis_script
        uses: andstor/file-existence-action@v3
        with:
          files: "crear_instalador_windows.nsi"

      - name: Install NSIS
        if: steps.check_nsis_script.outputs.files_exists == 'true'
        run: choco install nsis -y

      - name: Build Windows Installer with NSIS
        if: steps.check_nsis_script.outputs.files_exists == 'true'
        run: makensis crear_instalador_windows.nsi
        working-directory: ./dynaRangePortable
        shell: bash

      - name: Upload Portable Version Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynaRange-Windows-Static-Portable
          path: dynaRangePortable/

      - name: Upload Windows Installer Artifact
        if: steps.check_nsis_script.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dynaRange-Windows-Installer
          path: dynaRangePortable/dynaRangeInstaller.exe